apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-config
  namespace: kube-system
data:
  my-scheduler-config.yaml: |
    kind: KubeSchedulerConfiguration
    apiVersion: kubescheduler.config.k8s.io/v1
    clientConnection:
      kubeconfig: /etc/kubernetes/my-scheduler/my-kubeconfig.yaml
    profiles:
      - schedulerName: my-scheduler
        plugins:
          # This is just an example based on https://github.com/kubernetes/kubernetes/blob/release-1.26/cmd/kube-scheduler/app/server_test.go
          multiPoint:
            enabled:
            - name: SchedulingGates
            - name: DefaultBinder
            - name: PrioritySort
            - name: DefaultPreemption
            - name: VolumeBinding
            - name: NodeResourcesFit
            - name: NodePorts
            - name: InterPodAffinity
            - name: TaintToleration
            # Enables custom plugins
            - name: multipoint-communicating-plugin
            - name: NodeNumber
              weight: 10
            disabled:
            - name: "*"
          filter:
            disabled:
            - name: VolumeBinding
            - name: InterPodAffinity
            - name: TaintToleration
  my-kubeconfig.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <Masked>
        server: https://192.168.49.2:8443
      name: mk
    contexts:
    - context:
        cluster: mk
        user: kubernetes-admin
      name: kubernetes-admin@mk
    current-context: kubernetes-admin@mk
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: <Masked>
        client-key-data: <Masked>