apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-config
  namespace: kube-system
data:
  my-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: my-scheduler
        plugins:
          # This is just an example based on https://github.com/kubernetes/kubernetes/blob/release-1.26/cmd/kube-scheduler/app/server_test.go
          multiPoint:
            enabled:
            - name: SchedulingGates
            - name: DefaultBinder
            - name: PrioritySort
            - name: DefaultPreemption
            - name: VolumeBinding
            - name: NodeResourcesFit
            - name: NodePorts
            - name: InterPodAffinity
            - name: TaintToleration
            disabled:
            - name: "*"
          filter:
            disabled:
            - name: VolumeBinding
            - name: InterPodAffinity
            - name: TaintToleration